version: "3"

services:
  resilience:
    build:
      context: app
      dockerfile: Dockerfiles/Dockerfile.dev
    entrypoint: ./entrypoint.local.sh
    ports:
      - 5000:5000
    volumes:
      - "./app:/opt/resilience_calculator"
