services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ghcr.io/idaholab/resdeeds/web
    container_name: resdeeds-web
    ports:
      - 80:80
      - 443:443
      - 4200:4200
    stdin_open: true
    tty: true
    volumes:
      - ./web:/var/www
      - node_modules:/var/www/node_modules
      - ./web/etc/ssl:/etc/ssl
      - ./web/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./web/etc/nginx/log:/var/log/nginx
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ghcr.io/idaholab/resdeeds/api
    container_name: resdeeds-api
    depends_on:
      - mongodb
    env_file:
      - ./api/.env
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    volumes:
      - ./api:/var/www
  mongodb:
    container_name: resdeeds-mongodb
    env_file:
      - ./api/.env
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  node_modules:
  mongodb_data:
