services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: resdeeds-web
    # depends_on:
    #   - api
    ports:
      - 4200:4200
    stdin_open: true
    tty: true
    volumes:
      - ./web:/var/www
      - node_modules:/var/www/node_modules
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: resdeeds-api
    env_file:
      - ./api/.env
    ports:
      - 5000:5000
    volumes:
      - ./api:/var/www

volumes:
  node_modules:
