services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ghcr.io/idaholab/resdeeds/web
    container_name: resdeeds-web
    ports:
      - 80:80
      - 443:443
      - 4200:4200
    stdin_open: true
    tty: true
    networks:
      - resdeeds-network
    volumes:
      - ./web:/var/www
      - node_modules:/var/www/node_modules
      - ./web/etc/ssl:/etc/ssl
      - ./web/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./web/etc/nginx/log:/var/log/nginx
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ghcr.io/idaholab/resdeeds/api
    container_name: resdeeds-api
    depends_on:
      - mongodb
    env_file:
      - ./api/.env
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    networks:
      - resdeeds-network
    volumes:
      - ./api:/var/www
  drawio:
    container_name: resdeeds-drawio
    image: jgraph/drawio:latest
    environment:
      - PUBLIC_URL=/drawio
      - DRAWIO_BASE_URL=/drawio
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./drawio:/config
    networks:
      - resdeeds-network
  mongodb:
    container_name: resdeeds-mongodb
    env_file:
      - ./api/.env
    image: mongo:8.0
    ports:
      - 27017:27017
    networks:
      - resdeeds-network
    volumes:
      - mongodb_data:/data/db

networks:
  resdeeds-network:
    driver: bridge

volumes:
  node_modules:
  mongodb_data:
