services:
  web:
    container_name: resdeeds-web
    image: ghcr.io/idaholab/resdeeds/web
    ports:
      - 80:80
      - 443:443
    networks:
      - resdeeds_network
    volumes:
      - ./etc/ssl:/etc/ssl
      - ./etc/nginx:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
  api:
    container_name: resdeeds-api
    image: ghcr.io/idaholab/resdeeds/api:latest
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - resdeeds_network
  mongodb:
    container_name: resdeeds-mongodb
    env_file:
      - .env
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - resdeeds_network
networks:
  resdeeds_network:
volumes:
  mongodb_data:
