
services:

  rescalc:
    image: rescalc
    build:
      context: .
      dockerfile: ./install/Dockerfile
    ports:
      - 5000:5000

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080