services:
  rescalc:
    build:
      context: .
    ports:
      - 5000:5000
#   db:
#     image: postgres:16
#     env_file: .env
#     ports:
#       - 5432:5432
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
