version: "3"

services:
  resilience:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.dev
    command: "tail -f /dev/null"
    ports:
      - 5000:5000
    volumes:
      - ".:/opt/resilience_calculator"
