FROM python:3.10

# OS binaries
RUN apt update && apt-get -y upgrade
RUN apt-get install -y libpq-dev libglib2.0-dev libgl-dev libxkbcommon-x11-0 libegl-dev build-essential libgl1-mesa-dev libdbus-1-3
RUN apt-get install -y wget python3 python3-pip git

# Source code
WORKDIR /opt/resilience_calculator
COPY . .

# App dependencies
RUN pip config set global.trusted-host \
    "pypi.org files.pythonhosted.org pypi.python.org"
RUN pip install -r requirements.dev.txt
RUN pip install -r requirements.git.txt

# Julia
WORKDIR /opt
RUN wget https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.3-linux-x86_64.tar.gz
RUN tar zxvf julia-1.9.3-linux-x86_64.tar.gz
ENV PATH=$PATH:/opt/julia-1.9.3/bin
RUN . ./resilience_calculator/install/julia.sh