FROM ubuntu:latest

# OS binaries
RUN apt update && apt-get -y upgrade
RUN apt-get install -y git

# Application
WORKDIR /opt
COPY . .
# RUN git clone --recurse-submodules https://github.inl.gov/miracle/resilience_calculator.git

# # Install
# RUN ./resilience_calculator/install/install.sh