name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE: ${{ secrets.IMAGE_URL }}
  PAT: ${{ secrets.PAT }}

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Registry login
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo $PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Docker Image (for cache)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker pull $IMAGE/api:latest || true

      - name: Build Docker Image
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker build -f Dockerfile . --tag $IMAGE/api:latest --cache-from $IMAGE/api:latest
          else
            docker build -f Dockerfile . --tag temp-api:${{ github.sha }}
          fi

      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push $IMAGE/api:latest

  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Registry login
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo $PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Docker Image (for cache)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker pull $IMAGE/web:latest || true

      - name: Build Docker Image
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker build -f Dockerfile . --tag $IMAGE/web:latest --cache-from $IMAGE/web:latest
          else
            docker build -f Dockerfile . --tag temp-web:${{ github.sha }}
          fi

      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push $IMAGE/web:latest
