name: maintest

on: []

jobs:
  build:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m jill install --confirm
        julia -e 'using Pkg; Pkg.rm("SpineInterface")' || true
        julia -e 'using Pkg; Pkg.rm("SpineOpt")' || true
        julia -e 'using Pkg; Pkg.add(url="https://github.com/spine-tools/SpineInterface.jl.git")'
        julia -e 'using Pkg; Pkg.add(url="https://github.com/spine-tools/SpineOpt.jl.git")'
        julia -e 'using Pkg; Pkg.add(["XLSX", "DataFrames", "Distributions", "CSV", "Revise", "Cbc", "Clp"])'
        mkdir -p ~/.config/SpineProject/
        cp "./install/Spine Toolbox.conf" ~/.config/SpineProject/
        python ./src/tests/set_secret.py
    - name: Running pytest
      run: |
        python3 -m pytest ./src/tests/test.py
